apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shopping-list.fullname" . }}-backend
  labels:
    {{- include "shopping-list.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shopping-list.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shopping-list.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.frontendImagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "shopping-list.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backendImage.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
          ports:
            - name: backend-http
              containerPort: 3001
              protocol: TCP
          envFrom:
          - secretRef:
              name: env-secret
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: backend-http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
