apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopping-list.fullname" . }}-frontend
  labels:
    {{- include "shopping-list.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: frontend-http
      protocol: TCP
      name: http
  selector:
    {{- include "shopping-list.selectorLabels" . | nindent 4 }}
